/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "InvestmentManagementService"
includeBuild("smithy-rs")
include(":models")
include("app")
include(":sdks:rust-servers")
include(":sdks:dart-clients")
include(":web_app")


buildscript {
    repositories {
        mavenCentral()
    }

    val smithyVersion: String by settings
    dependencies {
        classpath("software.amazon.smithy:smithy-aws-traits:$smithyVersion")
    }
}

plugins {
    id("software.amazon.smithy").version("0.6.0").apply(false)
    kotlin("jvm").version("1.6.10").apply(false)
}